### ISSUE TITLE
Support for keyfiles and automounting

### ISSUE THREAD

**Issue by crat0z** [rustybird/qubes-split-dm-crypt#1]
Hello, I'm not sure what the current state of this project is, but I figured I may as well ask anyway. Will there be support for keyfiles and automounting on startup? For example, I want to start my vault VM every time I turn on the computer, and attach drive like in this script. Previously, I used a 3 line script in dom0 that'd start vault VM on startup and assign drive, then an rc.local file that'd open the LUKS device and mount it. Of course it was a little hacky..

If you are busy right now, perhaps I'll work on it myself. Would you accept PRs, if they're well written?

**Comment by rustybird** [comment]
The [key-file branch](https://github.com/rustybird/qubes-split-dm-crypt/tree/key-file) has a new `--key-file=[<key-vm>:]<file>` option, please let me know if it works for you.

Automounting can be done in the destination VM's `/rw/config/rc.local`, independently of Split dm-crypt:

```
# for systemd >= 232 (e.g. Fedora >= 26, Debian >= 9, Arch):
systemd-mount --no-block -A /dev/disk/by-... /mnt/removable

# for older systemd:
echo /dev/disk/by-... /mnt/removable auto noauto,x-systemd.automount >/etc/fstab
systemctl daemon-reload
systemctl restart local-fs.target
```

**Comment by crat0z** [comment]
Yes that fix worked as I'd expect, but the Fedora >= 25 instructions didn't work for me, even though I've upgraded my template. Either way, thanks for the fix.

**Comment by rustybird** [comment]
Ah sorry, I thought Fedora 25 had systemd 232, not 231. Thanks for the feedback.
